# Site settings
title: Aesop For Entrepreneurs
email: aesop@aesopforentrepreneurs.com
description: > An exciting website
Foo
Bar Baz
baseurl: ""
url: "http://aesopforentrepreneurs.com"  site

twitter_username: aesop

# Build settings
markdown: kramdown
