# Site settings
title: Aesop For Entrepreneurs
email: "alex@aesopforentrepreneurs.com"
description: An exciting website
baseurl: ""
url: "http://www.aesopforentrepreneurs.com"
description: Become a successful entrepreneur through Aesop's fables
author: Alex Goldsborough
keywords: Aesop, Entreprenership, Founding, Business, Fables

# Build settings
markdown: kramdown
