# Site settings
title: Aesop For Entrepreneurs
email: "aesop@aesopforentrepreneurs.com"
description: An exciting website
baseurl: ""
url: "http://aesopforentrepreneurs.com"

twitter_username: aesop

# Build settings
markdown: kramdown
